from django.urls import path
from .views import  CargoListView, add_adotante, add_tipodespesa,RelListView,MaioAniListView,JunhoAniListView, RelAnimaisListView, MaioListView, JunhoListView, despesa_update, despesa_delete, cargo_update, despesa_detalhes, add_despesas, TipoDespesaListView, cargo_delete, add_cargo, add_funcionario, adm, DespesasListView, AnimaisListView, FuncListView, VoluntariosListView, add_doacao, DoacaoListView,doacao_update, doacao_delete,  add_voluntarios, func_update, voluntarios_delete, voluntarios_update, add_duvidas, user_update, user_delete, adotante_update, duvidas_delete, add_sobre, duvidas_update, sobre_update, sobre_delete, adotante_delete,  raca_update,  tipo_update, add_raca, raca_delete, add_animal, add_tipo, post_delete, tipo_delete, post_update, TipoListView, RacaListView, AdotanteListView, UsersListView, signup, SobreListView, DuvidasListView
from django.contrib.auth import views as auth_views

app_name = 'adm'

urlpatterns = [
    path('gerenciador/', adm.as_view(), name='gerenciador'),
    path('cad-aninal/', adm.as_view(), name='cad-animal'),
    path('animais/', AnimaisListView, name='list-animais'),
    path('editar/', adm.as_view, name='editar'),
    path('funcionarios/', FuncListView, name='funcionarios'),
    path('rel/animais/', RelAnimaisListView, name='animais'),
    path('rel/animais/maio/', MaioAniListView, name='maio'),
    path('rel/animais/junho/', JunhoAniListView, name='junho'),
    path('rel/despesas/', RelListView, name='despesas'),
    path('rel/despesas/maio/', MaioListView, name='maio'),
    path('rel/despesas/junho/', JunhoListView, name='junho'),
    path('despesas/', DespesasListView, name='despesas'),
    path('despesas/adicionar/', add_despesas, name='registrar'),
    path('despesas/editar/<int:id>/', despesa_update, name='editar'),
    path('despesas/delete/<int:id>/', despesa_delete, name='editar'),
    path('despesas/tipo/', TipoDespesaListView, name='tipo'),
    path('despesas/tipo/adicionar/', add_tipodespesa, name='registrar'),
    path('despesas/detalhes/<int:id>/', despesa_detalhes, name='detalhes'),
    path('funcionarios/adicionar/', add_funcionario, name='registrar'),
    path('funcionarios/editar/<int:id>/', func_update, name='editar'),
    path('cargo/', CargoListView, name='cargo'),
    path('cargo/adicionar/', add_cargo, name='registrar'),
    path('cargo/delete/<int:id>/', cargo_delete, name='delete'),
    path('cargo/editar/<int:id>/', cargo_update, name='editar'),
    path('animais/tipo/', TipoListView, name='tipo'),
    path('animais/raca/', RacaListView, name='raca'),
    path('animais/adotante/', AdotanteListView, name='adotante'),
    path('usuarios/', UsersListView, name='usuarios'),
    path('animais/sobre/', SobreListView, name='sob'),
    path('animais/duvidas/', DuvidasListView, name='duvidas'),
    path('voluntarios/adicionar/', add_voluntarios, name='registrar'),
    path('voluntarios/', VoluntariosListView, name='voluntarios'),
    path('voluntarios/editar/<int:id>/', voluntarios_update, name='editar'),
    path('voluntarios/delete/<int:id>/', voluntarios_delete, name='delele'),
    path('doacao/', DoacaoListView, name='doacao'),
    path('doacao/editar/<int:id>/', doacao_update, name='editar'),
    path('doacao/adicionar/', add_doacao, name='adicionar'),
    path('doacao/delete/<int:id>/', doacao_delete, name='delele'),
    path('usuarios/registrar/', signup, name='registrar'),
    path('animais/adicionar/', add_animal, name='adicionar'),
    path('usuarios/editar/<int:id>/', user_update, name='editar'),
    path('usuarios/delete/<int:id>/', user_delete, name='delele'),
    path('animais/editTodo/<int:id>/',post_update, name='editTodo'),
    path('animais/tipo/adicionar/', add_tipo, name='add_tipo'),
    path('animais/delete/<int:id>/', post_delete, name='delete'),
    path('animais/adotante/adicionar/', add_adotante, name='add_tipo'),
    path('animais/adotante/editar/<int:id>/', adotante_update, name='editar'),
    path('animais/adotante/delete/<int:id>/', adotante_delete, name='delete'),
    path('animais/sobre/editar/<int:id>/', sobre_update, name='editar'),
    path('animais/sobre/delete/<int:id>/', sobre_delete, name='delete'),
    path('animais/sobre/adicionar/', add_sobre, name='add_sobre'),
    path('animais/raca/adicionar/', add_raca, name='add_raca'),
    path('animais/duvidas/delete/<int:id>/', duvidas_delete, name='delete'),
    path('animais/duvidas/adicionar/', add_duvidas, name='add_duvidas'),
    path('animais/duvidas/editar/<int:id>/', duvidas_update, name='editar'),
    path('animais/raca/editar/<int:id>/', raca_update, name='editar'),
    path('animais/raca/delete/<int:id>/', raca_delete, name='delete'),
    path('animais/tipo/edittipo/<int:id>/',tipo_update, name='edittipo'),
    path('animais/tipo/delete/<int:id>/', tipo_delete, name='delete')
]