# Generated by Django 4.0.4 on 2022-06-15 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cargo', models.CharField(max_length=20, verbose_name='Cargo')),
            ],
            options={
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=80, verbose_name='Nome Completo')),
                ('Cpf', models.CharField(max_length=20, verbose_name='CPF')),
                ('Telefone', models.CharField(max_length=80, verbose_name='Telefone')),
                ('Email', models.EmailField(max_length=50, verbose_name='E-mail')),
                ('Cep', models.CharField(max_length=80, verbose_name='Cep')),
                ('Rua', models.CharField(max_length=25, verbose_name='Rua')),
                ('Bairro', models.CharField(max_length=80, verbose_name='Bairro')),
                ('Cidade', models.CharField(max_length=30, verbose_name='Cidade')),
                ('Estado', models.CharField(max_length=10, verbose_name='Estado')),
                ('Cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.cargo', verbose_name='Cargo')),
            ],
            options={
                'verbose_name_plural': 'Funcionários',
            },
        ),
    ]
