# Generated by Django 4.0.4 on 2022-06-04 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoAnimal', models.CharField(max_length=20, verbose_name='Tipo de Animal')),
            ],
            options={
                'verbose_name_plural': 'Tipos de Animais',
            },
        ),
        migrations.CreateModel(
            name='RacaAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RacaAnimal', models.CharField(max_length=30, verbose_name='Raça do Animal')),
                ('TipoAnimal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.tipoanimal', verbose_name='Tipo de Animal')),
            ],
            options={
                'verbose_name_plural': 'Raças',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField()),
                ('body', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='atualizado em')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('draft', 'Rascunho')], max_length=15)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
        ),
        migrations.CreateModel(
            name='Animais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeAnimal', models.CharField(max_length=80, verbose_name='Nome do Animal')),
                ('IdadeAnimal', models.CharField(max_length=10, verbose_name='Idade aproxima do Animal')),
                ('PesoAnimal', models.CharField(max_length=5, verbose_name='Peso do Animal')),
                ('CorAnimal', models.CharField(max_length=15, verbose_name='Cor do Animal')),
                ('SexoAnimal', models.CharField(choices=[('Macho', 'Macho'), ('Femea', 'Femea')], max_length=15, verbose_name='Sexo do Animal')),
                ('Vacinado', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=15, verbose_name='Vacinado?')),
                ('Adotado', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=15, verbose_name='Adotado?')),
                ('FotoCapaAnimal', models.ImageField(null=True, upload_to='media/', verbose_name='Foto de Capa')),
                ('Observacao', models.TextField(verbose_name='Observação')),
                ('ativo', models.BooleanField(default=True)),
                ('RacaAnimal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.racaanimal', verbose_name='Raça do Animal')),
                ('TipoAnimal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.tipoanimal', verbose_name='Tipo de Animal')),
            ],
            options={
                'verbose_name_plural': 'Animais',
            },
        ),
    ]
