# Generated by Django 4.0.4 on 2022-06-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeDoador', models.CharField(max_length=80, verbose_name='Nome Completo')),
                ('TelefoneDoador', models.CharField(max_length=20, verbose_name='Telefone')),
                ('EmailDoador', models.EmailField(max_length=80, verbose_name='E-mail')),
                ('TipoDoacao', models.CharField(choices=[('Alimento', 'Alimento'), ('Medicamentos', 'Medicamentos')], max_length=15, verbose_name='Tipo de Doação')),
                ('QtdDoacao', models.CharField(max_length=80, verbose_name='Qtd Doação')),
                ('CepDoador', models.CharField(max_length=25, verbose_name='Cep')),
                ('RuaDoador', models.CharField(max_length=80, verbose_name='Rua')),
                ('NumeroCasaDoador', models.CharField(max_length=6, verbose_name='Número')),
                ('BairroDoador', models.CharField(max_length=30, verbose_name='Bairro')),
                ('CidadeDoador', models.CharField(max_length=80, verbose_name='Cidade')),
                ('EstadoDoador', models.CharField(max_length=30, verbose_name='Estado')),
                ('Observacao', models.TextField(verbose_name='Observação')),
                ('DeAcordoDoador', models.BooleanField(default=False, verbose_name='Selecione para concordar')),
            ],
            options={
                'verbose_name_plural': 'Doadores',
            },
        ),
    ]
