# Generated by Django 4.0.4 on 2022-06-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duvidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=50, verbose_name='Pergunta Dúvida')),
                ('texto_pergunta', models.TextField(default='', verbose_name='Resposta')),
            ],
            options={
                'verbose_name_plural': 'Dúvidas',
            },
        ),
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30, verbose_name='Titulo da Pagina Sobre')),
                ('imagem_sobre', models.ImageField(null=True, upload_to='media/', verbose_name='Imagem Sobre')),
                ('texto_sobre', models.TextField(verbose_name='Texto Sobre do Site')),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Sobre',
            },
        ),
        migrations.CreateModel(
            name='Voluntarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeVoluntario', models.CharField(max_length=80, verbose_name='Nome Completo')),
                ('TelefoneVoluntario', models.CharField(max_length=10, verbose_name='Telefone')),
                ('EmailVoluntario', models.CharField(max_length=80, verbose_name='E-mail')),
                ('IdadeVoluntario', models.CharField(max_length=2, verbose_name='Idade')),
                ('TempoDisponivelHrsMes', models.CharField(max_length=3, verbose_name='Horas por mês de voluntariado')),
                ('CepVoluntario', models.CharField(max_length=5, verbose_name='Cep')),
                ('RuaVoluntario', models.CharField(max_length=15, verbose_name='Rua/Logradouro')),
                ('NumCasaVoluntario', models.CharField(max_length=80, verbose_name='Número')),
                ('BairroVoluntario', models.CharField(max_length=80, verbose_name='Bairro')),
                ('CidadeVoluntario', models.CharField(max_length=80, verbose_name='Cidade')),
                ('MensagemVoluntario', models.TextField(verbose_name='Observação')),
            ],
            options={
                'verbose_name_plural': 'Voluntários',
            },
        ),
    ]
