# Generated by Django 4.0.4 on 2022-06-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntarios',
            name='CepVoluntario',
            field=models.CharField(max_length=15, verbose_name='Cep'),
        ),
    ]
