# Generated by Django 4.0.4 on 2022-06-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_voluntarios_cepvoluntario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntarios',
            name='RuaVoluntario',
            field=models.CharField(max_length=50, verbose_name='Rua/Logradouro'),
        ),
        migrations.AlterField(
            model_name='voluntarios',
            name='TelefoneVoluntario',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
    ]
