# Generated by Django 4.0.4 on 2022-06-16 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoDespesa', models.CharField(max_length=20, verbose_name='Nome Despesa')),
            ],
            options={
                'verbose_name_plural': 'Despesas',
            },
        ),
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descricao', models.TextField(verbose_name='Descrição')),
                ('Valor', models.CharField(max_length=10, verbose_name='Valor')),
                ('criado_em', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('Quantidade', models.CharField(max_length=5, verbose_name='Quantidade')),
                ('Total', models.CharField(max_length=15, verbose_name='Total')),
                ('TipoDespesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='despesas.tipodespesa', verbose_name='Tipo de Despesa')),
            ],
        ),
    ]
