# Generated by Django 4.0.4 on 2022-06-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adotante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeAdotante', models.CharField(max_length=80, verbose_name='Nome Completo')),
                ('TelefoneAdotante', models.CharField(max_length=20, verbose_name='Telefone')),
                ('EmailAdotante', models.EmailField(max_length=80, verbose_name='E-mail')),
                ('CepAdotante', models.CharField(max_length=25, verbose_name='Cep')),
                ('RuaAdotante', models.CharField(max_length=80, verbose_name='Rua')),
                ('NumCasaAdotante', models.CharField(max_length=6, verbose_name='Número')),
                ('BairroAdotante', models.CharField(max_length=30, verbose_name='Bairro')),
                ('CidadeAdotante', models.CharField(max_length=80, verbose_name='Cidade')),
                ('EstadoAdotante', models.CharField(max_length=80, verbose_name='Estado')),
                ('AnimalAdotante', models.CharField(max_length=80, verbose_name='Animal escolhido')),
                ('ObsAdotante', models.TextField(verbose_name='Observação')),
            ],
        ),
    ]
